import os
import json

def get_files_recursively(directory, base_dir):
    """Recursively get all files in a directory"""
    files = []
    
    for root, dirs, filenames in os.walk(directory):
        for filename in filenames:
            file_path = os.path.join(root, filename)
            relative_path = os.path.relpath(file_path, base_dir)
            relative_path = relative_path.replace('\\', '/')
            
            files.append({
                "path": relative_path,
                "name": filename,
                "size": os.path.getsize(file_path)
            })
    
    return files

# Get the music directory path
script_dir = os.path.dirname(os.path.abspath(__file__))
# Go up from server/scripts to root, then into music
music_dir = os.path.join(script_dir, '..', '..', 'music')
music_dir = os.path.abspath(music_dir)

print(f"Looking for music directory at: {music_dir}")

if os.path.exists(music_dir):
    files = get_files_recursively(music_dir, music_dir)
    print(f"Found {len(files)} files")
else:
    print(f"Music directory not found, using empty list")
    files = []

# Generate Python file with embedded data in the api directory
api_dir = os.path.join(script_dir, '..', 'api')
output_path = os.path.join(api_dir, 'music_data.py')

with open(output_path, 'w') as f:
    f.write("# Auto-generated file - DO NOT EDIT\n")
    f.write("# Generated by scripts/build.py\n\n")
    f.write(f"MUSIC_FILES = {json.dumps(files, indent=2)}\n")

print(f"Generated {output_path} with {len(files)} files")